name       : tmate
version    : 2.4.0
release    : 10
source     :
    - https://github.com/tmate-io/tmate/archive/2.4.0.tar.gz : 62b61eb12ab394012c861f6b48ba0bc04ac8765abca13bdde5a4d9105cb16138
license    : BSD
component  : system.utils
summary    : A fork of tmux that provides an instant pairing solution.
description: |
    tmate is a fork of tmux. tmate and tmux can coexist on the same system.
builddeps  :
    - pkgconfig(libevent)
    - pkgconfig(msgpack)
    - pkgconfig(libssh)
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
