name       : tmate
version    : 2.2.1
release    : 5
source     :
    - https://github.com/tmate-io/tmate/archive/2.2.1.tar.gz : d9c2ac59f42e65aac5f500f0548ea8056fd79c9c5285e5af324d833e2a84c305
license    : BSD
component  : system.utils
summary    : A fork of tmux that provides an instant pairing solution.
description: |
    tmate is a fork of tmux. tmate and tmux can coexist on the same system.
builddeps  :
    - pkgconfig(libevent)
    - pkgconfig(msgpack)
    - pkgconfig(libssh)
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
